[features]
seeds = false
[programs.devnet]
monopoly = "monvVbcL8zas8HjPcx3FbHiAK4Nqi7VZrruM7gcyZin"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/arearae/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
